services:
  app:
    container_name: financ_statistic_app
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    restart: no
    depends_on:
      - db
    networks:
      - financ_statistic_app
    expose:
      - 8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:16
    container_name: financ_statistic_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    networks:
      - financ_statistic_app


volumes:
  postgres_data:

networks:
  financ_statistic_app: